import oracledb
from app.config import Config
import logging

# Set logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class Database:
    def __init__(self):
        self.connection = None
        self.connect()

    def connect(self):
        try:
            params = Config.get_connection_params()
            logger.info(f"Connecting to Oracle...")
            
            if 'user' in params and 'password' in params and 'service_name' in params:
                dsn = f"{params['host']}:{params['port']}/{params['service_name']}"
                self.connection = oracledb.connect(
                    user=params['user'],
                    password=params['password'],
                    dsn=dsn
                )
            elif 'user' in params and 'password' in params and 'dsn' in params:
                self.connection = oracledb.connect(
                    user=params['user'],
                    password=params['password'],
                    dsn=params['dsn']
                )
            else:
                self.connection = oracledb.connect(Config.DATABASE_URL)
            
            logger.info("Database connected successfully")
            
            cursor = self.connection.cursor()
            cursor.execute("SELECT 'Connection successful!' FROM DUAL")
            result = cursor.fetchone()
            cursor.close()
            
            if result:
                logger.info(f"Database connection verified: {result[0]}")
                self.create_tables()
            else:
                raise Exception("Database connection test failed")
                
        except oracledb.DatabaseError as e:
            error, = e.args
            logger.error(f"Database connection error: {error.message}")
            raise
        except Exception as e:
            logger.error(f"Database connection error: {str(e)}")
            raise

    def create_tables(self):
        cursor = self.connection.cursor()
        
        try:
            # Users table
            cursor.execute("""
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE users (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            email VARCHAR2(255) UNIQUE NOT NULL,
                            password_hash VARCHAR2(255) NOT NULL,
                            is_verified CHAR(1) DEFAULT ''N'',
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                        )
                    ';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN RAISE; END IF;
                END;
            """)
            logger.info("Users table created/verified successfully")
            
            # OTP table
            cursor.execute("""
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE otp_codes (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            email VARCHAR2(255) NOT NULL,
                            otp_code VARCHAR2(10) NOT NULL,
                            purpose VARCHAR2(20) NOT NULL,
                            expires_at TIMESTAMP NOT NULL,
                            is_used CHAR(1) DEFAULT ''N'',
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                        )
                    ';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN RAISE; END IF;
                END;
            """)
            logger.info("OTP table created/verified successfully")
            
            # NEW: Access token blacklist table
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE '
                            CREATE TABLE access_token_blacklist (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                token VARCHAR2(500) NOT NULL,
                                email VARCHAR2(255) NOT NULL,
                                expires_at TIMESTAMP NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                            )
                        ';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
                logger.info("Access token blacklist table created")
            except:
                pass
            
            # NEW: Refresh token blacklist table
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE '
                            CREATE TABLE refresh_token_blacklist (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                token VARCHAR2(500) NOT NULL,
                                email VARCHAR2(255) NOT NULL,
                                expires_at TIMESTAMP NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                            )
                        ';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
                logger.info("Refresh token blacklist table created")
            except:
                pass
            
            # Create indexes
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX idx_users_email ON users(email)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
            except:
                pass
            
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX idx_otp_email_purpose ON otp_codes(email, purpose)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
            except:
                pass
            
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX idx_otp_expires ON otp_codes(expires_at)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
            except:
                pass
            
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX idx_at_blacklist_token ON access_token_blacklist(token)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
            except:
                pass
            
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX idx_rt_blacklist_token ON refresh_token_blacklist(token)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                """)
            except:
                pass
            
            self.connection.commit()
            logger.info("All database objects created/verified successfully")
            
        except oracledb.DatabaseError as e:
            error, = e.args
            logger.error(f"Database error: {error.message}")
            self.connection.rollback()
            raise
        finally:
            cursor.close()

    def execute_query(self, query, params=None):
        cursor = self.connection.cursor()
        try:
            cursor.execute(query, params or {})
            self.connection.commit()
            return cursor
        except oracledb.DatabaseError as e:
            error, = e.args
            logger.error(f"Query execution error: {error.message}")
            self.connection.rollback()
            raise
        except Exception as e:
            logger.error(f"Query execution error: {str(e)}")
            self.connection.rollback()
            raise

    def fetch_one(self, query, params=None):
        cursor = self.execute_query(query, params)
        try:
            result = cursor.fetchone()
            return result
        finally:
            cursor.close()

    def fetch_all(self, query, params=None):
        cursor = self.execute_query(query, params)
        try:
            result = cursor.fetchall()
            return result
        finally:
            cursor.close()

    def close(self):
        if self.connection:
            self.connection.close()
            logger.info("Database connection closed")

# Create global database instance
db = Database()